# Generated by Django 5.1.2 on 2024-10-13 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('course_description', models.TextField()),
                ('course_created_at', models.DateTimeField(auto_now_add=True)),
                ('course_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=150)),
                ('lesson_description', models.TextField()),
                ('course_number', models.IntegerField()),
                ('course_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses')),
            ],
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
                ('video_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('video_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courselessons')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson_evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.IntegerField(choices=[(1, 'yoqmadi'), (2, "chidasa bo'ladi"), (3, 'qoniqarli'), (4, 'yaxshi'), (5, "a'lo")])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lessonvideo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_to_lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lessonvideo')),
            ],
        ),
    ]
